In [1]:
from sklearn.datasets import load_breast_cancer
from numpy import genfromtxt
data = genfromtxt('./data/new_tag_nov20/cut_f_seb_1m_class_begin_t.csv', delimiter=',')


In [8]:
features = data[:,0:3]
labels = data[:,4:5]
labels = labels.astype(int).flatten()

In [14]:
features.shape

(695, 3)

In [15]:
from sklearn.model_selection import cross_val_score

Logistic 

In [16]:
from sklearn import linear_model
logistic = linear_model.LogisticRegression(C=1e5)
cross_val_score(logistic, features, labels, cv=10, n_jobs=-1)

array([ 0.83098592,  0.82857143,  0.82857143,  0.82857143,  0.84057971,
        0.84057971,  0.84057971,  0.84057971,  0.84057971,  0.84057971])

Gaussian NB 

In [17]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
cross_val_score(gnb, features, labels, cv=10, n_jobs=-1)

array([ 0.81690141,  0.81428571,  0.75714286,  0.65714286,  0.84057971,
        0.85507246,  0.84057971,  0.84057971,  0.84057971,  0.84057971])

KNN


In [18]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
cross_val_score(knn, features, labels, cv=10, n_jobs=-1)

array([ 0.8028169 ,  0.74285714,  0.67142857,  0.72857143,  0.85507246,
        0.8115942 ,  0.84057971,  0.84057971,  0.8115942 ,  0.84057971])

Linear SVM

In [19]:
from sklearn import svm
svc = svm.SVC(kernel='linear')
cross_val_score(svc, features, labels, cv=10, n_jobs=-1)

array([ 0.83098592,  0.82857143,  0.82857143,  0.82857143,  0.84057971,
        0.84057971,  0.84057971,  0.84057971,  0.84057971,  0.84057971])

SVM Radial Basis Function

In [20]:
from sklearn import svm
svc = svm.SVC(kernel='rbf')
cross_val_score(svc, features, labels, cv=10, n_jobs=-1)

array([ 0.83098592,  0.82857143,  0.82857143,  0.82857143,  0.84057971,
        0.84057971,  0.84057971,  0.84057971,  0.84057971,  0.84057971])

Random Forest

In [21]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()
cross_val_score(clf, features, labels, cv=10, n_jobs=-1)

array([ 0.81690141,  0.77142857,  0.74285714,  0.74285714,  0.84057971,
        0.8115942 ,  0.84057971,  0.82608696,  0.86956522,  0.84057971])

Nerual Network

In [22]:
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(5, 2), random_state=1)
cross_val_score(clf, features, labels, cv=10, n_jobs=-1)

array([ 0.83098592,  0.82857143,  0.82857143,  0.82857143,  0.84057971,
        0.84057971,  0.84057971,  0.84057971,  0.84057971,  0.84057971])