In [1]:
from sklearn.datasets import load_breast_cancer
from numpy import genfromtxt
data = genfromtxt('./data/new_tag_nov20/f_seb_1m_class_begin_t.csv', delimiter=',')


In [2]:
features = data[:,0:3]
labels = data[:,4:5]
labels = labels.astype(int).flatten()

In [3]:
features.shape

(1440, 3)

In [4]:
from sklearn.model_selection import cross_val_score

Logistic 

In [5]:
from sklearn import linear_model
logistic = linear_model.LogisticRegression(C=1e5)
cross_val_score(logistic, features, labels, cv=10, n_jobs=-1)

array([ 0.91724138,  0.91724138,  0.91724138,  0.91724138,  0.92361111,
        0.92361111,  0.92307692,  0.92307692,  0.92307692,  0.92307692])

Gaussian NB 

In [6]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
cross_val_score(gnb, features, labels, cv=10, n_jobs=-1)

array([ 0.86206897,  0.91724138,  0.91724138,  0.91724138,  0.89583333,
        0.92361111,  0.92307692,  0.92307692,  0.92307692,  0.92307692])

KNN


In [7]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
cross_val_score(knn, features, labels, cv=10, n_jobs=-1)

array([ 0.87586207,  0.90344828,  0.91034483,  0.91724138,  0.86805556,
        0.91666667,  0.92307692,  0.91608392,  0.92307692,  0.90909091])

Linear SVM

In [8]:
from sklearn import svm
svc = svm.SVC(kernel='linear')
cross_val_score(svc, features, labels, cv=10, n_jobs=-1)

array([ 0.91724138,  0.91724138,  0.91724138,  0.91724138,  0.92361111,
        0.92361111,  0.92307692,  0.92307692,  0.92307692,  0.92307692])

SVM Radial Basis Function

In [9]:
from sklearn import svm
svc = svm.SVC(kernel='rbf')
cross_val_score(svc, features, labels, cv=10, n_jobs=-1)

array([ 0.91724138,  0.91724138,  0.91724138,  0.91724138,  0.92361111,
        0.92361111,  0.92307692,  0.92307692,  0.92307692,  0.92307692])

Random Forest

In [10]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()
cross_val_score(clf, features, labels, cv=10, n_jobs=-1)

array([ 0.91034483,  0.91034483,  0.91724138,  0.91724138,  0.86111111,
        0.91666667,  0.91608392,  0.92307692,  0.92307692,  0.92307692])

Nerual Network

In [11]:
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(5, 2), random_state=1)
cross_val_score(clf, features, labels, cv=10, n_jobs=-1)

array([ 0.91724138,  0.91724138,  0.91724138,  0.91724138,  0.92361111,
        0.92361111,  0.92307692,  0.92307692,  0.92307692,  0.92307692])