In [1]:
from sklearn.datasets import load_breast_cancer
from numpy import genfromtxt
data = genfromtxt('./data/new_tag_nov20/cut_f_seb_1m_class_t.csv', delimiter=',')


In [2]:
features = data[:,0:3]
labels = data[:,4:5]
labels = labels.astype(int).flatten()

In [3]:
features.shape

(695, 3)

In [4]:
from sklearn.model_selection import cross_val_score

Logistic 

In [5]:
from sklearn import linear_model
logistic = linear_model.LogisticRegression(C=1e5)
cross_val_score(logistic, features, labels, cv=10, n_jobs=-1)

array([ 0.52857143,  0.37142857,  0.52857143,  0.44285714,  0.51428571,
        0.52857143,  0.5       ,  0.52173913,  0.51470588,  0.51470588])

Gaussian NB 

In [6]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
cross_val_score(gnb, features, labels, cv=10, n_jobs=-1)

array([ 0.51428571,  0.44285714,  0.51428571,  0.52857143,  0.71428571,
        0.47142857,  0.54285714,  0.63768116,  0.67647059,  0.57352941])

KNN


In [7]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
cross_val_score(knn, features, labels, cv=10, n_jobs=-1)

array([ 0.54285714,  0.52857143,  0.47142857,  0.54285714,  0.57142857,
        0.47142857,  0.5       ,  0.56521739,  0.60294118,  0.66176471])

Linear SVM

In [8]:
from sklearn import svm
svc = svm.SVC(kernel='linear')
cross_val_score(svc, features, labels, cv=10, n_jobs=-1)

array([ 0.51428571,  0.51428571,  0.51428571,  0.51428571,  0.51428571,
        0.51428571,  0.51428571,  0.52173913,  0.51470588,  0.51470588])

SVM Radial Basis Function

In [9]:
from sklearn import svm
svc = svm.SVC(kernel='rbf')
cross_val_score(svc, features, labels, cv=10, n_jobs=-1)

array([ 0.51428571,  0.51428571,  0.51428571,  0.51428571,  0.51428571,
        0.51428571,  0.51428571,  0.52173913,  0.51470588,  0.51470588])

Random Forest

In [10]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()
cross_val_score(clf, features, labels, cv=10, n_jobs=-1)

array([ 0.5       ,  0.4       ,  0.5       ,  0.5       ,  0.48571429,
        0.5       ,  0.44285714,  0.56521739,  0.61764706,  0.58823529])

Nerual Network

In [11]:
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(5, 2), random_state=1)
cross_val_score(clf, features, labels, cv=10, n_jobs=-1)

array([ 0.51428571,  0.51428571,  0.51428571,  0.51428571,  0.51428571,
        0.51428571,  0.51428571,  0.52173913,  0.51470588,  0.51470588])