In [1]:
from sklearn.datasets import load_breast_cancer
from numpy import genfromtxt
data = genfromtxt('./data/seb_1min_class_begin.csv', delimiter=',')


In [2]:
features = data[:,0:3]
labels = data[:,3:4]
labels = labels.astype(int).flatten()

In [3]:
features.shape


(1260, 3)

In [4]:
from sklearn.model_selection import cross_val_score

Logistic 

In [5]:
from sklearn import linear_model
logistic = linear_model.LogisticRegression(C=1e5)
cross_val_score(logistic, features, labels, cv=10, n_jobs=-1)

array([ 0.92125984,  0.91338583,  0.91269841,  0.91269841,  0.91269841,
        0.91269841,  0.91269841,  0.91269841,  0.92      ,  0.92      ])

Gaussian NB 

In [6]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
cross_val_score(gnb, features, labels, cv=10, n_jobs=-1)

array([ 0.91338583,  0.88976378,  0.91269841,  0.91269841,  0.91269841,
        0.91269841,  0.91269841,  0.91269841,  0.92      ,  0.92      ])

KNN


In [7]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
cross_val_score(knn, features, labels, cv=10, n_jobs=-1)

array([ 0.88188976,  0.88976378,  0.9047619 ,  0.91269841,  0.91269841,
        0.91269841,  0.9047619 ,  0.91269841,  0.912     ,  0.92      ])

Linear SVM

In [8]:
from sklearn import svm
svc = svm.SVC(kernel='linear')
cross_val_score(svc, features, labels, cv=10, n_jobs=-1)

array([ 0.91338583,  0.91338583,  0.91269841,  0.91269841,  0.91269841,
        0.91269841,  0.91269841,  0.91269841,  0.92      ,  0.92      ])

SVM Radial Basis Function

In [9]:
from sklearn import svm
svc = svm.SVC(kernel='rbf')
cross_val_score(svc, features, labels, cv=10, n_jobs=-1)

array([ 0.91338583,  0.91338583,  0.91269841,  0.91269841,  0.91269841,
        0.91269841,  0.91269841,  0.91269841,  0.92      ,  0.92      ])

Random Forest

In [10]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()
cross_val_score(clf, features, labels, cv=10, n_jobs=-1)

array([ 0.88976378,  0.85826772,  0.91269841,  0.91269841,  0.9047619 ,
        0.91269841,  0.91269841,  0.91269841,  0.92      ,  0.92      ])

Nerual Network

In [11]:
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(5, 2), random_state=1)
cross_val_score(clf, features, labels, cv=10, n_jobs=-1)

array([ 0.91338583,  0.91338583,  0.91269841,  0.91269841,  0.91269841,
        0.91269841,  0.91269841,  0.91269841,  0.92      ,  0.92      ])