In [1]:
from sklearn.datasets import load_breast_cancer
from numpy import genfromtxt
data = genfromtxt('./data/seb_1s_class_begin_less.csv', delimiter=',')


In [2]:
features = data[:,0:3]
labels = data[:,3:4]
labels = labels.astype(int).flatten()

In [3]:
features.shape


(32400, 3)

In [4]:
from sklearn.model_selection import cross_val_score

Logistic 

In [5]:
from sklearn import linear_model
logistic = linear_model.LogisticRegression(C=1e5)
cross_val_score(logistic, features, labels, cv=10, n_jobs=-1)

array([ 0.81487195,  0.81487195,  0.81512346,  0.81512346,  0.81512346,
        0.81512346,  0.81512346,  0.81512346,  0.81506638,  0.81506638])

Gaussian NB 

In [6]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
cross_val_score(gnb, features, labels, cv=10, n_jobs=-1)

array([ 0.83122493,  0.81302067,  0.81388889,  0.81512346,  0.81234568,
        0.81141975,  0.8132716 ,  0.81481481,  0.806113  ,  0.80734795])

KNN


In [7]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
cross_val_score(knn, features, labels, cv=10, n_jobs=-1)

array([ 0.76920703,  0.77630361,  0.77777778,  0.78580247,  0.78395062,
        0.78302469,  0.78580247,  0.77654321,  0.78450139,  0.79530719])

Linear SVM

In [8]:
from sklearn import svm
svc = svm.SVC(kernel='linear')
cross_val_score(svc, features, labels, cv=10, n_jobs=-1)

array([ 0.81487195,  0.81487195,  0.81512346,  0.81512346,  0.81512346,
        0.81512346,  0.81512346,  0.81512346,  0.81506638,  0.81506638])

SVM Radial Basis Function

In [9]:
from sklearn import svm
svc = svm.SVC(kernel='rbf')
cross_val_score(svc, features, labels, cv=10, n_jobs=-1)

array([ 0.81487195,  0.81487195,  0.81512346,  0.81512346,  0.81512346,
        0.81512346,  0.81512346,  0.81512346,  0.81506638,  0.81506638])

Random Forest

In [10]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()
cross_val_score(clf, features, labels, cv=10, n_jobs=-1)

array([ 0.79635915,  0.79419932,  0.79290123,  0.79259259,  0.79290123,
        0.7962963 ,  0.78919753,  0.79567901,  0.79221982,  0.79932078])

Nerual Network

In [11]:
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(5, 2), random_state=1)
cross_val_score(clf, features, labels, cv=10, n_jobs=-1)

array([ 0.81487195,  0.81487195,  0.81512346,  0.81512346,  0.81512346,
        0.81512346,  0.81512346,  0.81512346,  0.81506638,  0.81506638])