In [12]:
from sklearn.datasets import load_breast_cancer
from numpy import genfromtxt
data = genfromtxt('./data/seb_1s_class_begin.csv', delimiter=',')


In [13]:
features = data[:,0:3]
labels = data[:,3:4]
labels = labels.astype(int).flatten()

In [14]:
features.shape


(75600, 3)

In [15]:
from sklearn.model_selection import cross_val_score

Logistic 

In [16]:
from sklearn import linear_model
logistic = linear_model.LogisticRegression(C=1e5)
cross_val_score(logistic, features, labels, cv=10, n_jobs=-1)

array([ 0.91971961,  0.91481481,  0.91481481,  0.91481481,  0.91481481,
        0.91481481,  0.91481481,  0.91481481,  0.91481481,  0.91493584])

Gaussian NB 

In [17]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
cross_val_score(gnb, features, labels, cv=10, n_jobs=-1)

array([ 0.9169422 ,  0.89669312,  0.91137566,  0.91150794,  0.91283069,
        0.91309524,  0.91428571,  0.91481481,  0.91362434,  0.91414208])

KNN


In [18]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
cross_val_score(knn, features, labels, cv=10, n_jobs=-1)

array([ 0.89921968,  0.90542328,  0.91044974,  0.90846561,  0.90727513,
        0.90978836,  0.90873016,  0.90542328,  0.90820106,  0.90885038])

Linear SVM

In [19]:
from sklearn import svm
svc = svm.SVC(kernel='linear')
cross_val_score(svc, features, labels, cv=10, n_jobs=-1)

array([ 0.91482608,  0.91481481,  0.91481481,  0.91481481,  0.91481481,
        0.91481481,  0.91481481,  0.91481481,  0.91481481,  0.91493584])

SVM Radial Basis Function

In [20]:
from sklearn import svm
svc = svm.SVC(kernel='rbf')
cross_val_score(svc, features, labels, cv=10, n_jobs=-1)

array([ 0.91482608,  0.91481481,  0.91481481,  0.91481481,  0.91481481,
        0.91481481,  0.91481481,  0.91481481,  0.91481481,  0.91493584])

Random Forest

In [21]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()
cross_val_score(clf, features, labels, cv=10, n_jobs=-1)

array([ 0.90318741,  0.90740741,  0.91058201,  0.90873016,  0.90925926,
        0.91230159,  0.91243386,  0.90780423,  0.90873016,  0.91083477])

Nerual Network

In [22]:
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(5, 2), random_state=1)
cross_val_score(clf, features, labels, cv=10, n_jobs=-1)

array([ 0.91482608,  0.91481481,  0.91481481,  0.91481481,  0.91481481,
        0.91481481,  0.91481481,  0.91481481,  0.91481481,  0.91493584])