In [6]:
from sklearn.datasets import load_breast_cancer
from numpy import genfromtxt
data = genfromtxt('./data/seb_1s_class.csv', delimiter=',')


In [7]:
features = data[:,0:3]
labels = data[:,3:4]
labels = labels.astype(int).flatten()

In [8]:
features.shape


(75600, 3)

In [9]:
from sklearn.model_selection import cross_val_score

Logistic 

In [10]:
from sklearn import linear_model
logistic = linear_model.LogisticRegression(C=1e5)
cross_val_score(logistic, features, labels, cv=10, n_jobs=-1)

array([ 0.50019839,  0.59714324,  0.58571429,  0.58439153,  0.62116402,
        0.43386243,  0.37248677,  0.65886243,  0.69890197,  0.75883053])

Gaussian NB 

In [11]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
cross_val_score(gnb, features, labels, cv=10, n_jobs=-1)

array([ 0.52453379,  0.51699511,  0.46693122,  0.44695767,  0.45992063,
        0.4462963 ,  0.43664021,  0.45357143,  0.49318693,  0.47678264])

KNN


In [12]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
cross_val_score(knn, features, labels, cv=10, n_jobs=-1)

array([ 0.50152096,  0.53604021,  0.54470899,  0.55      ,  0.55145503,
        0.47248677,  0.43187831,  0.56878307,  0.61926181,  0.64188385])

Linear SVM

In [13]:
from sklearn import svm
svc = svm.SVC(kernel='linear')
cross_val_score(svc, features, labels, cv=10, n_jobs=-1)

array([ 0.549795  ,  0.549795  ,  0.54973545,  0.54973545,  0.54973545,
        0.54973545,  0.54973545,  0.54973545,  0.54980818,  0.54980818])

SVM Radial Basis Function

In [14]:
from sklearn import svm
svc = svm.SVC(kernel='rbf')
cross_val_score(svc, features, labels, cv=10, n_jobs=-1)

array([ 0.549795  ,  0.549795  ,  0.54973545,  0.54973545,  0.54973545,
        0.54973545,  0.54973545,  0.54973545,  0.54980818,  0.54980818])

Random Forest

In [15]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()
cross_val_score(clf, features, labels, cv=10, n_jobs=-1)

array([ 0.51739188,  0.54000794,  0.55621693,  0.55965608,  0.55701058,
        0.47089947,  0.43452381,  0.5771164 ,  0.6248181 ,  0.64889536])

Nerual Network

In [16]:
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(5, 2), random_state=1)
cross_val_score(clf, features, labels, cv=10, n_jobs=-1)

array([ 0.549795  ,  0.549795  ,  0.54973545,  0.54973545,  0.54973545,
        0.54973545,  0.54973545,  0.54973545,  0.54980818,  0.54980818])