In [2]:
from sklearn.datasets import load_breast_cancer
from numpy import genfromtxt
data = genfromtxt('./data/seb_1min_class.csv', delimiter=',')


In [3]:
features = data[:,0:3]
labels = data[:,3:4]
labels = labels.astype(int).flatten()

In [4]:
features.shape


(1260, 3)

In [5]:
from sklearn.model_selection import cross_val_score

Logistic 

In [7]:
from sklearn import linear_model
logistic = linear_model.LogisticRegression(C=1e5)
cross_val_score(logistic, features, labels, cv=10, n_jobs=-1)

array([ 0.46456693,  0.58267717,  0.55555556,  0.5952381 ,  0.58730159,
        0.5       ,  0.52380952,  0.56349206,  0.552     ,  0.64      ])

Gaussian NB 

In [8]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
cross_val_score(gnb, features, labels, cv=10, n_jobs=-1)

array([ 0.5511811 ,  0.56692913,  0.44444444,  0.42857143,  0.46031746,
        0.44444444,  0.45238095,  0.47619048,  0.552     ,  0.512     ])

KNN


In [9]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
cross_val_score(knn, features, labels, cv=10, n_jobs=-1)

array([ 0.61417323,  0.53543307,  0.58730159,  0.58730159,  0.5952381 ,
        0.46825397,  0.42063492,  0.68253968,  0.608     ,  0.728     ])

Linear SVM

In [10]:
from sklearn import svm
svc = svm.SVC(kernel='linear')
cross_val_score(svc, features, labels, cv=10, n_jobs=-1)

array([ 0.5511811 ,  0.5511811 ,  0.54761905,  0.54761905,  0.54761905,
        0.54761905,  0.54761905,  0.54761905,  0.552     ,  0.552     ])

SVM Radial Basis Function

In [11]:
from sklearn import svm
svc = svm.SVC(kernel='rbf')
cross_val_score(svc, features, labels, cv=10, n_jobs=-1)

array([ 0.5511811 ,  0.5511811 ,  0.54761905,  0.54761905,  0.54761905,
        0.54761905,  0.54761905,  0.54761905,  0.552     ,  0.552     ])

Random Forest

In [12]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()
cross_val_score(clf, features, labels, cv=10, n_jobs=-1)

array([ 0.62204724,  0.5984252 ,  0.55555556,  0.61111111,  0.55555556,
        0.47619048,  0.37301587,  0.6031746 ,  0.632     ,  0.68      ])

Nerual Network

In [13]:
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(5, 2), random_state=1)
cross_val_score(clf, features, labels, cv=10, n_jobs=-1)

array([ 0.5511811 ,  0.5511811 ,  0.54761905,  0.54761905,  0.54761905,
        0.54761905,  0.54761905,  0.54761905,  0.552     ,  0.552     ])